### ISSUE TITLE
Problem during installation / setup

### ISSUE THREAD

**Issue by sammie76-2** [Thyraz/Sonos-Kids-Controller#1]
Hello! I am trying to install Sonos Kids Controller.

During the setup when starting the command "ionic build --prod" this error message appears:

```
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-lyCHfB/angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.

        ng run app:build:production exited with exit code 127.
```
The error log says:

```
[Error] Error: NGCC failed.
    at NgccProcessor.process (/home/pi/Sonos-Kids-Controller-master/node_module$
    at compiler.hooks.environment.tap (/home/pi/Sonos-Kids-Controller-master/no$
    at SyncHook.eval [as call] (eval at create (/home/pi/Sonos-Kids-Controller-$
    at SyncHook.lazyCompileHook (/home/pi/Sonos-Kids-Controller-master/node_mod$
    at Object.webpack [as webpackFactory] (/home/pi/Sonos-Kids-Controller-maste$
    at createWebpack (/home/pi/Sonos-Kids-Controller-master/node_modules/@angul$
    at Object.runWebpack (/home/pi/Sonos-Kids-Controller-master/node_modules/@a$
    at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap [as project] $
    at SwitchMapSubscriber._next (/home/pi/Sonos-Kids-Controller-master/node_mo$
    at SwitchMapSubscriber.Subscriber.next (/home/pi/Sonos-Kids-Controller-mast$
    at /home/pi/Sonos-Kids-Controller-master/node_modules/@angular-devkit/build$
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Can you give me an advice? Thanks a lot in advance.

**Comment by sammie76-2** [comment]
Solved.

**Comment by NoTrace-Kai** [comment]
How did you solved that error?

**Comment by toO231** [comment]
In the tsclient.json the following must be added

 "enableIvy":false
 
Overall, it will look like this:
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {.
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy":false
  }
}
