### ISSUE TITLE
Build gets stuck at ionic build --prod

### ISSUE THREAD

**Issue by stepman0** [Thyraz/Sonos-Kids-Controller#66]
Hi @Thyraz,

I updated my docker repo to your latest version 1.6 - thanks for your fixes.

Unfortunately, the build does not suceed. It gets stuck at `ionic build --prod`. I tried node12, node14 and node16.

```
Step 7/17 : RUN ionic build --prod
 ---> Running in 157f9be309df
> ng run app:build:production
- Generating browser application bundles (phase: setup)...
(node:18) UnhandledPromiseRejectionWarning: Error: The target entry-point "@ionic-native/splash-screen" has missing dependencies:
 - @ionic-native/core

    at TargetedEntryPointFinder.findEntryPoints (file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:4616:13)
    at file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:5008:33
    at SingleProcessExecutorSync.doExecute (file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:14633:23)
    at file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:14654:35
    at SyncLocker.lock (file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:14884:14)
    at SingleProcessExecutorSync.execute (file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:14654:19)
    at mainNgcc (file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:15985:19)
    at Module.process2 (file:///sonos-kids-controller/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:16050:10)
    at NgccProcessor.processModule (/sonos-kids-controller/node_modules/@ngtools/webpack/src/ngcc_processor.js:167:27)
    at /sonos-kids-controller/node_modules/@ngtools/webpack/src/ivy/host.js:146:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

Any hint?

[build-log-node14.txt](https://github.com/Thyraz/Sonos-Kids-Controller/files/8047402/build-log-node14.txt)

**Comment by HeikoGr** [comment]
i managed to compile it in WSL2 (Ubunutu 20.04) on Windows 11. 
but i was using nodejs v 16.

i just setup an github action which also compiles:
https://github.com/HeikoGr/Sonos-Kids-Controller/actions/runs/1828624874

according to github:
Node 16.13.2

I'm wondering if (and why) you override the package.json file?
`Step 4/17 : COPY src/package.json /sonos-kids-controller/package.json`

Your log file sent this related warnings:

```
npm WARN @ionic-native/splash-screen@5.36.0 requires a peer of @ionic-native/core@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/status-bar@5.36.0 requires a peer of @ionic-native/core@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@12.2.16 requires a peer of @angular/compiler-cli@^12.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@12.2.16 requires a peer of typescript@~4.2.3 || ~4.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@12.2.16 requires a peer of @angular/compiler-cli@^12.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@12.2.16 requires a peer of typescript@~4.2.3 || ~4.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nice-napi@1.0.2 (node_modules/nice-napi):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nice-napi@1.0.2 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by stepman0** [comment]
I figured it out: I used the alpine-images of node, but with the normal (debian?) edition of v16 it works.

@HeikoGr : The copying of package.json is a leftover, when I update dependencies before they are integrated into the main repository.
